name: Deploy VCrypto to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            if [ ! -d "vcrypt-project" ]; then
              git clone https://github.com/${{ github.repository }} vcrypt-project
            fi
            cd vcrypt-project
            git pull origin main
            docker-compose down
            docker-compose up -d --build
